channels:
  - defaults
dependencies:
  - pandas=1.5.3
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - numpy=1.24.3
  - netCDF4=1.6.2
  - cftime=1.6.2
  - scipy=1.10.1
  - scikit-learn=1.2.2
  - joblib=1.1.1
  - statsmodels=0.14.0